# Generated by Django 6.0 on 2026-01-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_remove_material_texture_material_description_and_more'),
        ('orders', '0002_orderrequest_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='material',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='material',
            field=models.ManyToManyField(blank=True, to='customization.material', verbose_name='Selected Materials'),
        ),
    ]
