# Generated by Django 6.0 on 2026-01-05 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('orders', '0003_remove_orderrequest_material_orderrequest_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.project', verbose_name='Project'),
        ),
    ]
