# Generated by Django 6.0 on 2026-01-05 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_remove_material_texture_material_description_and_more'),
        ('orders', '0004_orderrequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='depth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Depth (mm)'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (mm)'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customization.pattern', verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Width (mm)'),
        ),
    ]
