# Generated by Django 6.0 on 2026-01-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hero_title', models.CharField(default='Меблі вашої мрії в Івано-Франківську', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(blank=True, default='Індивідуальний підхід до кожного клієнта. Створюйте затишок разом з нами.', verbose_name='Hero Subtitle')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Hero Background Image')),
                ('contact_phone', models.CharField(default='+38 (0XX) XXX-XX-XX', max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('address', models.CharField(default='м. Івано-Франківськ, вул. ...', max_length=255, verbose_name='Address')),
                ('working_hours', models.CharField(default='Пн-Пт: 9:00 - 18:00', max_length=100, verbose_name='Working Hours')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Settings',
                'verbose_name_plural': 'Home Settings',
            },
        ),
    ]
