# Generated by Django 6.0 on 2026-01-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='custom_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Custom Section Image'),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='why_us_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='Why Us Section Image'),
        ),
    ]
