# Generated by Django 6.0 on 2026-01-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='texture',
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Image'),
        ),
    ]
