# Generated by Django 6.0 on 2026-01-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('customization', '0002_remove_material_texture_material_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_materials',
            field=models.ManyToManyField(blank=True, related_name='products', to='customization.material', verbose_name='Available Materials'),
        ),
    ]
