# Generated by Django 6.0 on 2026-01-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_available_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Show on Home Page'),
        ),
    ]
